### PR TITLE
Fix "View Preview" Button Visibility for CSV Datasets

### LINKED ISSUE #200: Bug: Missing "View Preview" Button for CSV Datasets
### What's Happening
When a buyer searches and finds a CSV dataset, the **"View Preview (5%)"** button doesn't show up. Currently, this feature is only rendering for Excel files.

### The Root Cause
In `SearchData.tsx`, the preview button's visibility check evaluates whether the file type includes the string "spreadsheet" (`fileType?.includes('spreadsheet')`). 

Because CSV files have a MIME type of `text/csv` or `application/csv`—neither of which contains the word "spreadsheet"—the condition evaluates to false. As a result, this check silently excludes all CSV files from displaying a preview.

### Where the Bug Is Located
* **File:** `nextjs-frontend/components/SearchData.tsx`
* **Line:** 677

### Code Snippet
**Current code (Broken for CSV):**
```tsx
{result.metadata?.previewHash && result.metadata?.fileType?.includes('spreadsheet') && (
```

### PR DESCRIPTION
**Pull request by santhil-cyber**
### Summary
This PR fixes a bug where CSV files were not displaying the "View Preview" button on the search page. 

Previously, the code only checked for `spreadsheet` in the file type. Because CSV files have a MIME type of `text/csv`, the button remained hidden. A condition checking for `csv` has now been added. Additionally, text references have been updated from "Excel Preview" to "Data Preview" since the feature now supports both file types.

### Why This is Important
Buyers purchasing CSV datasets need the ability to preview the data prior to purchase, just like they do with Excel files. This ensures feature parity and makes CSV workflows function correctly on the platform.

### Changes Made
* **`SearchData.tsx`:** Added a check for `csv` alongside the existing `spreadsheet` check in the `fileType` evaluation.
* **Modal Title:** Changed the preview modal title to "Data Preview".
* **Success Message:** Updated the success message text to say "Data preview" instead of "Excel preview".

closes #200

### CODE REVIEW

File: nextjs-frontend/components/SearchData.tsx [hunk 1]
```diff
@@ -673,8 +673,8 @@ export default function SearchData({ onBack }: SearchDataProps) {
                           
                           {/* Action Buttons */}
                           <div className="flex justify-end gap-3 pt-4 border-t border-gray-200">
-                            {/* Preview Button for Excel files */}
-                            {result.metadata?.previewHash && result.metadata?.fileType?.includes('spreadsheet') && (
+                            {/* Preview Button for spreadsheet/CSV files */}
+                            {result.metadata?.previewHash && (result.metadata?.fileType?.includes('spreadsheet') || result.metadata?.fileType?.includes('csv')) && (
```
Comment (pradeeban) [inline nextjs-frontend/components/SearchData.tsx]: I am unsure of this addition. Can't the file be of type xls, xlsx, tsv, ... extensions, in that case?

**Comment by pradeeban** [comment]
Pls check the above comment.

File: nextjs-frontend/components/SearchData.tsx (hunk 1 above)
Comment (santhil-cyber) [reply nextjs-frontend/components/SearchData.tsx]: good point sir! i checked and you're right ... the `fileType` stored in metadata is the browser MIME type and `includes('spreadsheet')` actually only covers `.xlsx` and `.ods`. other formats like `.xls`, `.tsv`, `.xlsm`, `.xlsb` all don't contain the string `spreadsheet` either, so those were already broken before.

i think the cleanest fix here is to just check if `previewHash` exists without any `fileType` filtering since `previewHash` is only generated during upload for spreadsheet/csv files anyway (in `UploadData.tsx`), its existence already proves the file is previewable.

File: nextjs-frontend/components/SearchData.tsx [hunk 2]
```diff
@@ -294,8 +294,8 @@ export default function SearchData({ onBack }: SearchDataProps) {
         const previewInfo = {
           fileName: result.metadata?.fileName || `document_${index + 1}`,
           fileSize: bytes.length,
-          dataType: result.metadata?.fileType || 'Excel file',
-          message: 'Excel preview data loaded successfully. This is a 5% sample of the anonymized dataset.',
+          dataType: result.metadata?.fileType || 'Spreadsheet file',
+          message: 'Data preview loaded successfully. This is a 5% sample of the anonymized dataset.',
```
Comment (pradeeban) [inline nextjs-frontend/components/SearchData.tsx]: I think, we should still say "Spreadsheet" preview here. Data could be an image like DICOM or PNG. Right? That gets too vague and confusing.

File: nextjs-frontend/components/SearchData.tsx [hunk 3]
```diff
@@ -739,7 +739,7 @@ export default function SearchData({ onBack }: SearchDataProps) {
               <div className="flex items-center justify-between p-6 border-b border-gray-200 bg-gradient-to-r from-blue-50 to-indigo-50">
                 <h3 className="text-2xl font-bold text-gray-800 flex items-center gap-3">
                   <Eye size={24} className="text-blue-600" />
-                  Excel Preview (5% Sample)
+                  Data Preview (5% Sample)
```
Comment (pradeeban) [inline nextjs-frontend/components/SearchData.tsx]: I think, we should still say "Spreadsheet" preview here. Data could be an image like DICOM or PNG. Right? That gets too vague and confusing.

File: nextjs-frontend/components/SearchData.tsx [hunk 4]
```diff
@@ -673,8 +673,8 @@ export default function SearchData({ onBack }: SearchDataProps) {
                           
                           {/* Action Buttons */}
                           <div className="flex justify-end gap-3 pt-4 border-t border-gray-200">
-                            {/* Preview Button for Excel files */}
-                            {result.metadata?.previewHash && result.metadata?.fileType?.includes('spreadsheet') && (
+                            {/* Preview Button — previewHash is only generated for previewable files (spreadsheets, CSV) during upload */}
```
Comment (pradeeban) [inline nextjs-frontend/components/SearchData.tsx]: I think, saying                            "{/* Preview Button for Spreadsheets */}" is sufficient. right? We don't show all the files. Only the spreadsheets. Is that right?

Comment (santhil-cyber) [reply nextjs-frontend/components/SearchData.tsx]: Yes, you're right about the wording. I’ve updated it to say `Spreadsheet`.

While reviewing the flow, I also found that stored preview generation was still limited to `.xlsx` and `.xls` during upload, so I updated that to cover the supported spreadsheet formats as well. That way the CSV/spreadsheet preview works end-to-end instead of only at render time.

File: nextjs-frontend/components/SearchData.tsx (hunk 2 above)
Comment (santhil-cyber) [reply nextjs-frontend/components/SearchData.tsx]: You're right @pradeeban  "Data Preview" is too vague since the platform handles images (DICOM, PNG) too. I've updated both the modal title and the success message to say "Spreadsheet" instead. I've pushed the fix in the latest commit.

File: nextjs-frontend/components/SearchData.tsx (hunk 3 above)
Comment (santhil-cyber) [reply nextjs-frontend/components/SearchData.tsx]: You're right @pradeeban  "Data Preview" is too vague since the platform handles images (DICOM, PNG) too. I've updated both the modal title and the success message to say "Spreadsheet" instead. I've pushed the fix in the latest commit.
